server:
  port: 81

# 配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ruiyeclub.cn/boot_hello?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin

  redis:
    database: 0
    host: localhost
    port: 6379

# 配置sql打印日志
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.ruiyeclub.entity.*

